### ISSUE TITLE
Would it be easier to store [[Realm]] instead of [[LegacyRegExpConstructor]]?

### ISSUE THREAD

**Issue by domenic** [claudepache/es-regexp-legacy-static-properties#11]
It turns out in all implementations, all objects (not just functions) have a [[Realm]] slot.

We may eventually make this change in the specs, but for now I wanted to ask: would the spec be simpler if it stored the regexp's creation realm, instead of LegacyRegExpConstructor? I'm not entirely sure I understand the exact desired semantics for the cross-realm checks, but my naive expectation would be that cross-realm checks are easily done if the object stores its realm. It would probably also be easier to implement.

/cc @erights

**Comment by claudepache** [comment]
The [[LegacyRegExpConstructor]] may also have the value **undefined** (precisely when the regexp is an instance of a proper subclass of RegExp), signifying that the RegExp static properties must never be updated. So, [[Realm]] is not a sufficient replacement of [[LegacyRegExpConstructor]].

However, one can use, instead of [[LegacyRegExpConstructor]], two internal slots, namely [[Realm]] and [[LegacyRegExpFeaturesEnabled]], the latter holding a Boolean value. That would have the advantage, for the reader of the spec, of separating clearly these two features:  (1) Disabling the legacy functionalities for proper subclasses of RegExp, and (2) Preventing cross-realm interaction. Because implementations have a [[Realm]] slot anyway, that would in practice not augment the number of internal slots relatively to the current text of the proposal.

Are you in favor of this change?

**Comment by domenic** [comment]
Now that you've explained it (thanks!) I'd be happy with either the suggested change, or with an explanatory note explaining the dual purpose of the single slot. I guess I have a slight preference for two slots but I don't feel strongly.

**Comment by erights** [comment]
I prefer the two slots. Once the existence of the `[[Realm]]` slot is codified in spec language, I am sure we'll find other uses for it.
